### ISSUE TITLE
ImperviousSurface - IMPERV_ID Not Generating within the Export

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#10]
**Steps to Reproduce Error:**
Reporting Year = 2017 or 2018 or 2019
On Failure = Continue on Errors
Current User = KCI\Juanita.Miles

The IMPERV_ID field is not generating any values for any Reporting Year selected within the UI.

The ImperviousSurface.IMPERV_ID should populate using the following translation:

"BA" + YY + IMPERVIOUS_NUM
Where YY = 2 Rightmost characters of AR_IMPERVIOUS_SURFACE.REPORTING_YEAR

The source table, AR_IMPERVIOUS_SURFACE.IMPERVIOUS_NUM, contains valid data to generate the ID. 

MDE Export:
![image](https://user-images.githubusercontent.com/31770504/30975238-c4c5a846-a43f-11e7-92cb-1589274a39cf.png)

Source Table:
![image](https://user-images.githubusercontent.com/31770504/30976257-5dd35a54-a442-11e7-8503-7e8d67ac8084.png)

**Comment by gerrykelly** [comment]
Fixed, please test in next run and close issue if agreed
