### ISSUE TITLE
ImperviousSurface - Export Layer Name Exports in All Caps

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#11]
**Steps to Reproduce:**
Reporting Year = 2017
On Failure: Continue on Errors
Current User: KCI\Juanita.Miles

Within the MDE schema the table name should appear as "ImperviousSurface," but when the export is run the table name exports as "IMPERVIOUSSURFACE."

The all caps name is inconsistent with the other layer/table names exported into the MDE Schema.

Example of the Exported Table Names:
![image](https://user-images.githubusercontent.com/31770504/30976949-1ef371a0-a444-11e7-9e73-b387b351aa5c.png)

**Comment by gerrykelly** [comment]
Fixed, please test in next run and close issue if agreed
