### ISSUE TITLE
MDE Export - Feature Dataset Not Populating With Any Feature Classes in the Export

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#13]
**Steps to Reproduce:**
Reporting Year = 2017
On Failure = Continue On Errors
User = KCI\Juanita.Miles

The past few exports I have ran have not included any feature classes. Only tables are being included within the export. 
![image](https://user-images.githubusercontent.com/31770504/31227789-3060aef2-a9a9-11e7-8791-4056518d26d6.png)

The database should export as it appears below with all of the geometry layers or the "Append_Failure" layers.
![image](https://user-images.githubusercontent.com/31770504/31227759-0bb02416-a9a9-11e7-8c7d-8f56be19df50.png)  

I had Lee run an export and he has confirmed the same results. It appears as though the problem began on 9/27 sometime between 2:30pm and 9:30pm. As the export ran at 2:30 worked fine, and included the feature classes and the one I ran at 9:30 did not include them.

I have searched through the messages log to see if I could identify a message that would indicate why a feature class is not being exported, but all messages appear to show that it was successfully appended or it has created an "Append_Failure" feature class. See examples for AltBMPPoly and QuarterlyGradingPermits below.

![image](https://user-images.githubusercontent.com/31770504/31229203-f091face-a9ad-11e7-889f-e7643d81fc0f.png)

![image](https://user-images.githubusercontent.com/31770504/31229289-2f45d2e0-a9ae-11e7-88e1-76a194d75022.png)

**Comment by gerrykelly** [comment]
Should be fixed now
