### ISSUE TITLE
Spelling Error in UI - "Contunue On Errors"

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#14]
Within the "Export to MDE" tool:

The _Continue On Errors_ option from the On Failure pick list is currently spelled "Contunue On Errors."

Change spelling to "Continue On Errors"

![image](https://user-images.githubusercontent.com/31770504/31394712-0097c860-adad-11e7-8314-c25dd90a7659.png)

**Comment by leeensminger** [comment]
Resolved
