### ISSUE TITLE
AltBMPPoly (Impervious Removal) - Verify Translation of PROJECT_NAME is Acceptable

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#16]
For Impervious Removal the AltBMPPoly.PROJECT_NAME field is sourced from IMPERVIOUS_REM.STRU_NO_EPS.

IMPERVIOUS_REM.STRU_NO_EPS has a Double data type that is translated into a String field. Therefore, the Project Name is given a ".0" at the end. Example below:

Source Data (IMPERVIOUS_REM.STRU_NO_EPS):
![image](https://user-images.githubusercontent.com/31770504/31401965-7f7577d0-adc2-11e7-8849-7752e63a5649.png)

MDE Export (AltBMPPoly.PROJECT_NAME):
![image](https://user-images.githubusercontent.com/31770504/31402011-a22a1e84-adc2-11e7-943d-62ef7462a5fe.png)

Please confirm if this translation is okay. Or if it should export without the ".0" appended to the end.

**Comment by leeensminger** [comment]
@JuanitaMiles the ".0" suffix should be not be present.  @gerrykelly should strip the ".0" before inserting the string into the target field.

Just to expand - there are some STRU_NO_EPS values that include a decimal value - so it's important we strip this so we are consistent and accurate.

**Comment by gerrykelly** [comment]
Should be fixed (and I made one of the values 10.1 to make sure we do get decimal numbers when valid)
