### ISSUE TITLE
AltBMPPoly (Trees) - ACRES_PLANTED Data Type Mismatch

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#18]
TREE_AREAS.ACRES_PLANTED is a Double field type. The target within the MDE db, AltBMPPoly_ACRES_PLANTED, is a small integer field type.

Upon export the source acres planted is rounded to the nearest whole number. I do not see any direction that the acres planted should be rounded within the ETL documentation.

Source (TREE_AREAS.ACRES_PLANTED):
![image](https://user-images.githubusercontent.com/31770504/31415223-08221480-adf0-11e7-9b38-120b8d5113be.png)

MDE Export (AltBMPPoly.ACRES_PLANTED):
![image](https://user-images.githubusercontent.com/31770504/31415250-3b5f0da8-adf0-11e7-845a-df50648c1b04.png)

**Please confirm whether this rounding is correct, or if it is an issue.**

**Comment by leeensminger** [comment]
@JuanitaMiles Yes this is a function of the design of MDE's database.  We are forced to round to the nearest integer due to the target field type.... OK as-is.
