### ISSUE TITLE
QuarterlyGradingPmtInfo - All Domain Fields Populating With Codes Rather Than Descriptions in Export

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#19]
Steps to Reproduce:
Reporting Year = 2017
On Failure = Continue On Errors
Current User = KCI\Juanita.Miles

The following fields are being populated with the domain code rather than the domain description:
QuarterlyGradingPmtInfo.LAND_USE_BF
QuarterlyGradingPmtInfo.OWNER_STATE
QuarterlyGradingPmtInfo.QUARTER
QuarterlyGradingPmtInfo.SITE_STATE
QuarterlyGradingPmtInfo.WATERSHED8DGT
*QuarterlyGradingPmtInfo.LAND_USE_AF should most likely be added to this list as well, however no values are being populated in this field. (See separate logged issue "QuarterlyGradingPmtInfo - LAND_USE_AF No Values Populating in Export).

Examples of Error:
Source (QRT_GRADING_INFO.LAND_USE_BF):
![image](https://user-images.githubusercontent.com/31770504/31449819-ec17134a-ae75-11e7-9e7f-599b93f0f808.png)
MDE Export (QuarterlyGradingPmtInfo.LAND_USE_BF)
![image](https://user-images.githubusercontent.com/31770504/31449873-0cdef58e-ae76-11e7-844f-33011fe8ce74.png)

Source (QRT_GRADING_INFO.OWNER_STATE):
![image](https://user-images.githubusercontent.com/31770504/31450222-dbc85ce6-ae76-11e7-9735-601402ffb9fe.png)
MDE Export (QuarterlyGradingPmtInfo.OWNER_STATE):
![image](https://user-images.githubusercontent.com/31770504/31450257-f78d7d30-ae76-11e7-98d0-d0f0c2c4f687.png)

**Comment by gerrykelly** [comment]
@JuanitaMiles @leeensminger 
Not sure what's happening here.
1)  It is correct that the codes being written to the field, that's how it should work (i.e. state fields are only two characters)
2) But if the domain exists in the DB and the domain is applied to the field, you should see the descriptions.
3) And the domains are in the DB and applied from my checking:
![image](https://user-images.githubusercontent.com/8259136/31453097-ef7bb244-ae7e-11e7-808d-39f73c80c813.png)

I'll work on figuring this out but if you see anything that provides a clue, let me know

**Comment by gerrykelly** [comment]
@leeensminger @JuanitaMiles @BC89 
Let's make this a topic for Friday's meeting.  I have tried many things to restore the field-domain-code/description connection and nothing has worked.

**Comment by gerrykelly** [comment]
@JuanitaMiles @BC89 @leeensminger 
It looks like this was serendipitously resolved with addressing that erroneous subtype issue in the MDE table.
