### ISSUE TITLE
AltBMPPoint - No Values Populating For IMPL_COMP_YR in the Export

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#22]
Steps to Reproduce:
Reporting Year = 2017
On Failure = Continue On Errors
Current User = KCI\Juanita.Miles

AltBMPPoint.IMPL_COMP_YR should be populated using SEPTIC_SYSTEMS.IMPL_YEAR. The values from the source are not being populated.

Source (SEPTIC_SYSTEMS.IMPL_YEAR):
![image](https://user-images.githubusercontent.com/31770504/31453838-7bbf100a-ae81-11e7-959d-c4a50d61502a.png)
MDE Export (AltBMPPoint.IMPL_COMP_YR):
![image](https://user-images.githubusercontent.com/31770504/31453861-91d78444-ae81-11e7-9694-a1b9db37bbb6.png)

**Comment by gerrykelly** [comment]
Should be fixed (I did not test), please check on next run.
