### ISSUE TITLE
Stormwater - Update selection set logic for IMPL_STATUS

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#24]
In addition to the existing selection set logic, all BMPs should also be selected for where:

SW_TRACKING.IMPL_STATUS = Complete OR Planning OR Under Construction OR Abandoned OR Design OR Removed 

[all domain values should go to MDE, except Duplicate Record, Plan Revised, and Unknown]

This applies to all 4 major groups of BMPs - from Lee's ETL spreadsheet - 
- BMPs - New Development
- BMPs - Redevelpopment / Restoration
- BMPs - Conversions
- BMPs - POIS

**Comment by gerrykelly** [comment]
Ready for test after next GP service update

**Comment by leeensminger** [comment]
Appears resolved
