### ISSUE TITLE
Stormwater - Update selection set logic for BMP Status

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#25]
In addition to the existing selection set logic, all BMPs should also be selected for where:

BMPS.BMP_STATUS = Active OR Removed

[all domain values should go to MDE, except Proposed, Cancelled, Duplicate]

This applies to all 4 major groups of BMPs - from Lee's ETL spreadsheet -

BMPs - New Development
BMPs - Redevelpopment / Restoration
BMPs - Conversions
BMPs - POIS

**Comment by gerrykelly** [comment]
@leeensminger 
This should be working.  Probably not worth testing until I've done more on SW

**Comment by leeensminger** [comment]
Appears resolved
