### ISSUE TITLE
Stormwater - target RestBMP - source selection set does not consider Reporting Year

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#26]
The source selection set does not appear to include Reporting Year.  Selection set should be where:

SW_TRACKING.REPORTING_YEAR <= user selected reporting year

To identify this, I:
1. Join from the outputted "Append_Failure1_RestBMP_p_to_RestBMP" (which appears to be the selection set for where Con Purpose = Restoration or Redevelopment), back to the source.BMPS feature class [using Append_Failure1_RestBMP_p_to_RestBMP.BMP_ID_ORIG]
2. Find related SW_TRACKING records 

![image](https://user-images.githubusercontent.com/4103847/32286489-016c02c0-bf04-11e7-980a-97bef70bdeec.png)

**Comment by leeensminger** [comment]
Actually this appears to be the case for several other BMP selection sets as well.  When you identify a fix, do a double check on the other selections, and then I'll retest subsequent outputs for specific updates.

**Comment by gerrykelly** [comment]
Should be good now ... pending your review

**Comment by leeensminger** [comment]
Resolved
