### ISSUE TITLE
Outfalls - Update translations for new domains

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#28]
In [balt_co_npdes issue 239](https://github.com/kcigeospatial/balt_co_npdes/issues/239), three domains were affected with new codes/descriptions:
D_Outfall_Material - affects ETL, see translations below
D_Outfall_Type - affects ETL, see translations below
D_Outfall_Shape - does not affect ETL.  no translation needed.

I will also update my source documentation.

NCT_Domain_Name | NCT_Code | NCT_Description | MDE_Domain | MDE_Code
-- | -- | -- | -- | --
D_Outfall_Material | Brick | Brick | dOutfallMaterial | OTH
D_Outfall_Material | Concrete | Concrete | dOutfallMaterial | CONC
D_Outfall_Material | Metal | Metal | dOutfallMaterial | CMP
D_Outfall_Material | Plastic | Plastic | dOutfallMaterial | HDPE
D_Outfall_Material | Wood | Wood | dOutfallMaterial | OTH
D_Outfall_Material | Rubber | Rubber | dOutfallMaterial | OTH
D_Outfall_Material | Unknown | Unknown | dOutfallMaterial | UNK
D_Outfall_Material | Other | Other | dOutfallMaterial | OTH
D_Outfall_Type | End Section | End Section | dOutfallType | ES
D_Outfall_Type | End Support Wall | End Support Wall | dOutfallType | EW
D_Outfall_Type | Type A Endwall | Type A Endwall | dOutfallType | EW
D_Outfall_Type | Type B Endwall | Type B Endwall | dOutfallType | EW
D_Outfall_Type | Type C Endwall | Type C Endwall | dOutfallType | EW
D_Outfall_Type | Type E Endwall | Type E Endwall | dOutfallType | EW
D_Outfall_Type | Flap Gate | Flap Gate | dOutfallType | OTH
D_Outfall_Type | Wingwall | Wingwall | dOutfallType | EW
D_Outfall_Type | Duckbills | Duckbills | dOutfallType | OTH
D_Outfall_Type | Unknown | Unknown | dOutfallType | OTH
D_Outfall_Type | Other | Other | dOutfallType | OTH
D_Outfall_Type | Unconveyed Sump | Unconveyed Sump | dOutfallType | OTH

**Comment by leeensminger** [comment]
self assigning this, as it is ON HOLD until review by the County

**Comment by leeensminger** [comment]
@gerrykelly See County-approved field mappings above

**Comment by gerrykelly** [comment]
I committed these few changes to Oracle

**Comment by leeensminger** [comment]
Tested and confirmed OK
