### ISSUE TITLE
D_BMP_Status > dBMPStatus domain mapping

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#3]
dBMPStatus now only has 2 values: ACT | Active & REM | Removed

D_BMP_Status has 5
Active
Cancelled
Duplicate
Proposed
Removed

I know you're giving me info on this, so I'll leave it as is (but delete the existing PROP code for dBMPStatus from domains_baltco_mde_equivalency

**Comment by leeensminger** [comment]
Active ==> ACT
Cancelled ==> None (these will be removed from the selection set, see #25 )
Duplicate ==> None (these will be removed from the selection set, see #25 )
Proposed ==> None (these will be removed from the selection set, see #25 )
Removed ==> REM

**Comment by gerrykelly** [comment]
With that clarification, should be good as-is:
![image](https://user-images.githubusercontent.com/8259136/32298698-5885c094-bf29-11e7-9fbb-b0e8970c9b78.png)

**Comment by leeensminger** [comment]
The Active and Removed values appear to be good and translate correctly.  The other values (Cancelled, Duplicate, Proposed) still are outputted, when they shouldn't be, per issue #25 .   So I'm closing this, since these two values are good.
