### ISSUE TITLE
AltBMPLine - Verify MDE 2017 Schema Updates Are Reflected in ETL Templates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#30]
We need to verify the following fields in AltBMPLine within the MDE ETL Template are set to allow Null values:
Project Address
Project City
Project State
Project Zip
LU County

It appears as though a IMPL_COST field has been added to this layer in the 2017 MDE Schema Updates. We need to verify whether or not an IMPL_COST field needs to be added into the ETL Template.

**Comment by JuanitaMiles** [comment]
@gerrykelly Within AltBMPLine in the MDE template database, the following fields need to be updated to allow null values: PROJECT_CITY; PROJECT_STATE; PROJECT_ZIP; LU_COUNTY.

We also need to add a field IMPL_COST - Short Integer - Non-Nullable to AltBMPLine in the MDE Template.

I can make these updates if you would like me to as I did before. Not sure if anything would be different when adding a whole new field that you would need to take note of in any scripts. If you'd like me to make the updates, let me know if I should make the update in both templates (MDE_empty_withDomains; MDE_empty_withDomains_unaltered) or just one?

**Comment by leeensminger** [comment]
@JuanitaMiles,  it looks like this these changes were implemented.  Please confirm and close if agreed.

Looking at \\vm-wsscmta\c$\Projects\BaltCoNPDES\ETL\Templates\MDE_empty_withDomains.gdb
