### ISSUE TITLE
AltBMPLine - Nullable Mismatch Between Several Fields Causing Export Failure

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#31]
I have identified several fields that have a nullable mismatch and as a result may be the cause of an "Append Failure" in the ETL export. Fields include:
PROJECT_NAME
PROJECT_DESC
EQU_IMP_ACR
INSTALL_DATE
LENGTH_RESTORED
IMPL_COST (this field may not be in the ETL template at all)

Data gaps span across all ALTBMP types; Outfall Stabilization, Shoreline Restoration, and Stream Stabilization. I believe all data within NPDES.ALT_LINES source layer is migrated data, therefore I have not filled any data gaps with arbitrary values. It appears as though the data will translate properly to the MDE export once non-nullable fields are populated as needed. 

We will need to discuss how to move forward with these data gaps, as they will continue to cause an export failure of the entire AltBMPLine layer.

**Comment by leeensminger** [comment]
@JuanitaMiles 

Can you confirm that this list is the complete list of nullable mismatches?  We will give this to the County for their data management activities.

We do not need to handle this in the ETL.  This is a data management activity for the County to perform.

We DO need to test that these fields migrate successfully when populated.  Edit the SDE data as needed - regardless of whether or not it is migrated data.

**Comment by JuanitaMiles** [comment]
@leeensminger 
The complete list of potential nullable mismatches that could occur and cause errors are as follows. All of the 'Source' layers allow nulls while all of the 'Target' layers do not allow nulls.
Source: ALT_LINE_NUM --> Target: ALTBMP_LN_ID
Source: ALT_LINE_TYPE --> Target: ALTBMP_TYPE
Source: SITE_NAME --> Target: PROJECT_NAME
Source: PROJECT_DESC --> Target: PROJECT_DESC
Source: EQU_IMP_ACR --> Target: EQU_IMP_ACR
Source: INSTALL_DATE --> Target: INSTALL_DATE
Source: LENGTH_REST --> Target: LENGTH_REST
Source: IMPL_COST --> Target: IMPL_COST
