### ISSUE TITLE
ChemicalMonitoring - WATER_TEMP Not Exporting Correctly

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#32]
Steps to Reproduce:
Reporting Year: 2017
User: Juanita.Miles
Continue On Errors

ChemicalMonitoring.WATER_TEMP is not being exported correctly from MONITORING_CHEM.WATER_TEMP. 
Source (MONITORING_CHEM.WATER_TEMP)
![image](https://user-images.githubusercontent.com/31770504/32506272-1a17859e-c3b2-11e7-9572-fae28acc67b3.png)

Target (ChemicalMonitoring.WATER_TEMP)
![image](https://user-images.githubusercontent.com/31770504/32506296-2b8e7102-c3b2-11e7-8b03-7a0fc3899d3b.png)

The ETL documentation appears to have the wrong Soure field listed.
![image](https://user-images.githubusercontent.com/31770504/32506385-68fd8b36-c3b2-11e7-916e-76ad0fdd3197.png)

The documentation should instead list the following as the source:
![image](https://user-images.githubusercontent.com/31770504/32506485-b35a6b72-c3b2-11e7-982c-dccfdcf672d8.png)

**Comment by gerrykelly** [comment]
should be OK now
