### ISSUE TITLE
AltBMPLine - Need to Map IMPL_COST field

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#34]
Per the updated 2017 MDE schema, an IMPL_COST field needs to be added to the AltBMPLine feature class within the MDE database export. I have added the field to the revised MDE Template already, I'm guessing that you'll need to include it in the script to have it export? The fields map as follows:

Source Name: ALT_LINES.IMPL_COST
Source Type: Double
Source Nullable: Yes

Target Name: AltBMPLine.IMPL_COST
Target Type: Short Integer
Target Nullable: No

**Comment by gerrykelly** [comment]
@JuanitaMiles 
This done and working, but with the data I am testing on the append fails (one project name is 26 char when the MDE limit is 25, and there are null required values).  I'm not sure if that is what you are seeing in AGS, but if so that needs to be addressed.
Test after my next GP service update.

**Comment by JuanitaMiles** [comment]
@gerrykelly 
I think the problem may lie with the TSS/TN/TP fields in the MDE template. According to the MDE schema document these fields are "conditional" which I believe this should mean that the fields should allow for null values since some records should remain null if they don't meet a certain condition. Sorry I didn't catch this before. 

I did however change all of the Site Name records to be under 25 characters, so hopefully that takes care of that potential issue. 

@leeensminger 
Lee can you confirm that "conditional" fields in the MDE schema documentation should equate to Nullable = yes? 

I will make this update to the revised MDE Template once confirmed.

**Comment by leeensminger** [comment]
@JuanitaMiles Yes conditional = nullable.

**Comment by leeensminger** [comment]
OK
