### ISSUE TITLE
Outfalls - No Intersection Between Watershed and Land Use Reference Layers

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#35]
One Outfall point appears to not intersect with the 8dgt watershed and land use reference layers. As a result, these fields remain Null, and the MDE schema does not support null values for 8dgt Watershed and Land Use, causing an append failure in the MDE export.

How are we handling instances when a feature doesn't intersect a required reference layer? The export of the Outfall layer will continue to fail if these fields are not populated...

**Comment by gerrykelly** [comment]
@leeensminger @JuanitaMiles 
This is already raised in issue #9

**Comment by leeensminger** [comment]
Agreed, closing this one as a result

**Comment by leeensminger** [comment]
Also, confirmed this with Rob H. as the best way forward.
