### ISSUE TITLE
AltBMPPoly - Street Sweeping - Update selection set for Implementation Status

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#37]
The selection set for Street Sweeping needs to be updated for the new domain values in D_Impl_Status. Values Duplicate Record, Plan Revised, and Unknown need to be excluded from the selection set, so they don't go to MDE.

**The original selection set was:**

All ANNUAL_PRACTICE_AREAS records where :
- REPORTING_YEAR <= user selected reporting year
- ALTPOLY_TYPE = Mechanical Street Sweeping or Regenerative/Vacuum Street Sweeping

**So the new selection set is:**

All ANNUAL_PRACTICE_AREAS records where :
- REPORTING_YEAR <= user selected reporting year
- ALTPOLY_TYPE = Mechanical Street Sweeping or Regenerative/Vacuum Street Sweeping
- IMPL_STATUS = Complete OR Planning OR Under Construction OR Abandoned OR Design OR Removed [all domain values except Duplicate Record, Plan Revised, and Unknown]

**Comment by gerrykelly** [comment]
Ready for test after next GP service update

**Comment by leeensminger** [comment]
Cannot test until street sweeping comes through on the export

**Comment by leeensminger** [comment]
Appears resolved
