### ISSUE TITLE
AltBMPPoints - Septic Systems - Update selection set for Implementation Status

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#39]
The selection set for Septic Systems needs to be updated for the new domain values in D_Impl_Status. Values Duplicate Record, Plan Revised, and Unknown need to be excluded from the selection set, so they don't go to MDE.

**The original selection set was:**

All SEPTIC_SYSTEMS records where :
- REPORTING_YEAR <= user selected reporting year

**So the new selection set is:**

All SEPTIC_SYSTEMS records where :
- REPORTING_YEAR <= user selected reporting year
- IMPL_STATUS = Complete OR Planning OR Under Construction OR Abandoned OR Design OR Removed [all domain values except Duplicate Record, Plan Revised, and Unknown]

**Comment by gerrykelly** [comment]
Ready for test after next GP service update

**Comment by leeensminger** [comment]
Looks ok
