### ISSUE TITLE
D_Impl_Status > dlmpStatus mapping

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#4]
Another one where I know you'll give me more info later (just making an issue so we don't forget and not making any changes for now), but we have matches in dlmpStatus for:
  Complete
  Planning
  Under Construction
but not for 
  Abandoned
  Design
  Duplicate Record
  Plan Revised
  Removed
  Unknown

**Comment by leeensminger** [comment]
Abandoned ==> C
Design ==> P
Duplicate Record ==> None (this gets removed during the selection set, see #24 )
Plan Revised ==> None (this gets removed during the selection set, see #24 )
Removed ==> C
Unknown ==> None (this gets removed during the selection set, see #24 )

**Comment by gerrykelly** [comment]
Done; domain matching as below (from domains_baltco_mde_equivalency)

![image](https://user-images.githubusercontent.com/8259136/32298540-e9db056e-bf28-11e7-9e06-38bdca1c7e5d.png)

**Comment by leeensminger** [comment]
@gerrykelly This doesn't seem to be working correctly - can you take another look?  I created the following, that all derive from this issue (I created all of these before I saw this issue and remembered that we had already identified this):

Stormwater #24 
Inlet Cleaning #36
Street Sweeping #37
Impervious Removal #38
Septic Systems #39 
AltLines #33 

Feel free to close this if you want to track this at the more granular strategy-level.

**Comment by gerrykelly** [comment]
All  Ready for test after next GP service update

**Comment by leeensminger** [comment]
Closing to track at the more granular issues identified above
