### ISSUE TITLE
RestBMPs generate error feature class when there is no selection set

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#41]
For RestBMPs, it seems the ETL generates the error feature classes _Append_Failure_RESTBMP_p_to_RESTBMP_ and _Append_Failure1_RESTBMP_p_to_RESTBMP_, even when there is no RestBMP selection set.  If there is no valid selection set, the system generates these two feature classes with zero records (empty fc). 

The issue is that these two feature classes shouldn't be generated, if there is are no records expected to be exported.

**Comment by leeensminger** [comment]
[ETL_All_WarningsAndErrors_log.txt](https://github.com/kcigeospatial/balt_co_ETL/files/1545782/ETL_All_WarningsAndErrors_log.txt)
[ETL_All_Messages_log.txt](https://github.com/kcigeospatial/balt_co_ETL/files/1545783/ETL_All_Messages_log.txt)
Attached are the two error logs for this situation.  The error logs do not indicate what the error is that is causing the issue with RestBMPs.  See bottom of text file.

**Comment by leeensminger** [comment]
@gerrykelly still seems to be an issue when running the ETL for selection set 1A - whereby no records in RestBMP would be expected in the target output.

**Comment by leeensminger** [comment]
Just ran selection set 1B - where no BMP or BMPPOI output records would be expected, and found that an Append_Failure_RESTBMP and Append_Failure_BMP entities were exported.  So this seems to be more wide spread than the title suggests.

Definitely deprioritize this issue, as its really just an appearance issue - and the use case of not having one of the selection sets is rare.

**Comment by leeensminger** [comment]
@gerrykelly still needs to be fixed this week if possible, but deprioritize behind the other functional issues.

**Comment by gerrykelly** [comment]
@leeensminger  This should be fixed now

**Comment by leeensminger** [comment]
Looks good
