### ISSUE TITLE
Stormwater - BMPPOI - All source BMP_POIS records exported to output (selection set is not correct)

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#42]
For the BMPPOI feature class output, the selection set returns features that are outside of the intended selection set.  The selection set logic from the original spreadsheet is below.  The output database returns ALL records in the BMP_POIS feature class.  

Test case details:  Selection set = "new development", when there are no source BMP_POIS records related to valid BMPS records.  
 - In the specific source dataset I'm looking at, I have 6 SW_TRACKING records that are valid for export and expected in the output, and these are related to 6 BMPS records.  The ETL should take the geometry from the 6 source BMPS, and insert to the target BMPPOI feature class.  No records in the source BMP_POIS feature are related to a valid source BMP record, so none of the 17 total records in source BMP_POIS should be exported to the output.

_****original selection set logic from spreadsheet ****_
    □ SW Tracking is only used to identify the correct Con Purpose - no other attributes are taken from this table
    □ Find where:
        ® SW_TRACKING.REPORTING_YEAR <= user selected reporting year, and
        ® SW_TRACKING.TRACKING_STATUS = Current, and
        ® SW_TRACKING.CON_PURPOSE = New Development
    □ Find associated records in BMPS, where BMPS.BMP_STATUS <> Proposed.  From BMPS, find associated records in BMP_POIS.
    □ Load geometry for MDE.BMP_POI from NCT.BMP_POIS; load tabular data as specified in ETL worksheet.  Each NCT.BMPS feature class record will be loaded into MDE.BMP table.
    □ Ancillary translations
     □ For all NCT.BMP_POIS migrated, find associated NCT.BMP_DAS.  Load these into MDE.BMPDrainageArea.

**Comment by gerrykelly** [comment]
Should be good now ... pending your review
