### ISSUE TITLE
Stormwater - New Development - BMP table selection set returns more records than expected

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#43]
The ETL does not appear to query the selection set properly for source BMPS, so when it attempts to append to the target schema, the append fails consistently.  If the selection set logic was properly applied, the resulting records have good data, and should append successfully.  I think the selection set is missing the query for Reporting Year.

**Test details:**
1. Values for all records for SW_TRACKING.REPORTING_YEAR were set to null.  Values for all records for BMPS.REPORTING_YEAR were set to null.
2. For one record in SW_TRACKING, set SW_TRACKING.REPORTING_YEAR = 2017, and ensured all field values were good and valid.  Found the associated record in BMPs, and set BMPS.REPORTING_YEAR = 2017, and ensured all field values were good and valid.  Ensured a valid inspection and drainage area were present (in case that mattered for this test, though it shouldn't).
3. Ensured no records were associated to BMP_POIS.  All values for BMP_POIS.REPORTING_YEAR were set to null.
4. Ran ETL.
5. BMPs table failed, resulting in  _Append_Failure_BMP_p_to_BMP_ and  _Append_Failure_BMPS_to_BMP_ tables. 

**Results:**
Within the _Append_Failure_BMP_p_to_BMP_ table, ALL source BMP feature class records are present (count = 8167), with all attributes.  The one feature which had a valid Reporting Year is the only feature feature that successfully joined the SW_TRACKING record to it's source BMPS record.  So, I think the system is trying to append all 8167 records, and since only 1 joined, most of the values are null and the append fails.  This is the _Append_Failure_BMP_p_to_BMP_ table... the selected record is the only feature expected to be outputted, and it is the only one that should be in the resulting join table:
![image](https://user-images.githubusercontent.com/4103847/33807965-a0d0561a-ddac-11e7-9297-528b1bbab83d.png)

**Comment by gerrykelly** [comment]
Should be good now ... pending your review

**Comment by leeensminger** [comment]
Using this selection on source.SW_TRACKING, I get 4058 results (be aware that one of these still has a dupe SW_TRACK_ID that is not included in the 4058):

1. Remove all SW_TRACKING records related to source.BMP_POIS
1a. Select from source.BMPS, where: BMP_POI_ID IS NULL
1b. From source.BMPS, find all related source.SW_TRACKING records.

2. Select from SW_TRACKING
2a. From results of 1b, _Select from current selection_, and apply this query:
IMPL_STATUS NOT IN ( 'Plan Revised', 'Duplicate Record', 'Unknown') AND REPORTING_YEAR = '2017' AND TRACKING_STATUS <> 'Archived' AND CON_PURPOSE = 'New Development' 

Of these, I found all were migrated into the output (either BMP table, or the append_failure_bmp table) except 1133 records.  Those records are exported here: 
M:\2016\181603168.02\Reports\MDE_ETL\Testing\Stormwater\Outputs_forGerry\Issue_43.gdb\SelectionSet_1A_bmps_not_migrated_1133

At this time I am not sure why these were not included in the selection set.  The total intended selection set is here:
M:\2016\181603168.02\Reports\MDE_ETL\Testing\Stormwater\Outputs_forGerry\Issue_43.gdb\SelectionSet_intended_selection_set_all_4058

**Comment by leeensminger** [comment]
Closing since this issue appears fixed.  The selection set is still not quite fixed, but a new bug was created for that item as #59
