### ISSUE TITLE
Stormwater - Drainage Areas - ETL returns more records than expected

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#45]
Possibly related to #43 .  This issue should probably be addressed AFTER 43.

There are 6889 total BMP DA's in the source database.  The system outputs all 6889.  Only those drainage areas that relate to a valid, exported BMP should be similarly exported.  Note that for this test, all DA records have null Reporting Year.  I think the ETL does not need to consider Reporting Year in DAs, since the selection set is based entirely from exported Stormwater BMPs.

The ETL does not seem to consider this relationship at this time - as, currently, the ETL errors on the BMP export and does not successfully export any, but all 6889 DAs are exported.

**Comment by gerrykelly** [comment]
Should be good now ... pending your review

**Comment by leeensminger** [comment]
Appears resolved
