### ISSUE TITLE
Stormwater - RestBMP - LAST_CHANGE is not calculated for target database

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#47]
For the output data field RestBMP.LAST_CHANGE, the system should calculate values as the current system date at the time of processing.  Currently, values are outputted as null in this field (target field is required).

This same logic is also present for BMPPOI, and it is working correctly there in some instances.  See #49 for details of the circumstances in which this datestamp logic works correctly.

**Comment by gerrykelly** [comment]
Ready for test after next GP service update

**Comment by leeensminger** [comment]
Appears resolved
