### ISSUE TITLE
Stormwater - BMPPOI - LAST_CHANGE is not calculated for target database

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#49]
For the output data field BMPPOI.LAST_CHANGE, the system should calculate values as the current system date at the time of processing.  Currently, values are outputted as null in this field (target field is required).

Note, that currently, as described in #42, all source BMP_POIS are incorrectly migrated to the MDE output.  For these records, LAST_CHANGE is correctly populated - so this datestamp is working there (though the selection set logic is incorrect).

The LAST_CHANGE datastamp logic is also present in RestBMP, and it is not working there either.  See #47 .

**Comment by gerrykelly** [comment]
Ready for test after next GP service update

**Comment by leeensminger** [comment]
Looks OK
