### ISSUE TITLE
D_Con_Purpose > dConPurpose ... no match for Revitalization

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#5]
For now I'll use REST

**Comment by leeensminger** [comment]
This sounds reasonable, but I don't know the answer for sure.  I need to confirm with the County.

**Comment by leeensminger** [comment]
Per Rob Hirsch 20171212:

Stormwater features with a ConPurpose = Revitalization should be outputted to RestBMP, with a target Con Purpose = New Development ("NEWD").  

This pertains to selection set 1B (Restoration/Redevelopment) if you're following along in the original spreadsheet.

**The existing selection set for the target RestBMP feature class is:**

Find where:
 -SW_TRACKING.REPORTING_YEAR <= user selected reporting year, and
 -SW_TRACKING.TRACKING_STATUS = Current, and
 -SW_TRACKING.CON_PURPOSE = Restoration OR Redevelopment

**So the updated selection set for the target RestBMP feature class is:**

Find where:
 -SW_TRACKING.REPORTING_YEAR <= user selected reporting year, and
 -SW_TRACKING.TRACKING_STATUS = Current, and
 -SW_TRACKING.CON_PURPOSE = Restoration OR Redevelopment OR Revitalization

Translate source.CON_PURPOSE of "Revitalization" ==> target.CON_PURPOSE = "NEWD" [New Development]

**Comment by gerrykelly** [comment]
@leeensminger 
I made these changes.  Probably not worth testing until I've done more on SW

**Comment by leeensminger** [comment]
lee testing - RST003442

**Comment by leeensminger** [comment]
Resolved
