### ISSUE TITLE
Stormwater - BMPPOI - Update source of geometry when the feature is a POI

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#50]
When a source BMPS feature is related to a source BMP_POIS, the system should use the BMP_POIS geometry to load to the output.  The source BMPS geometry should be ignored.

Currently, the system appears to be using source.BMPS as the geometry source for target.BMPPOIS in these cases.

**Comment by gerrykelly** [comment]
per our discussion, I think I have this right ... so that for the 2 BMPs from selection set 1d relate to a single POI feature in the MDE export (and is it only set 1d where this logic is applied, or is that just a function of our test data?)

**Comment by leeensminger** [comment]
Looks OK
