### ISSUE TITLE
Stormwater - BMPPOI - Update source of target.BMPPOI.BMPPOI_ID to apply "POI"

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#52]
When a source BMPS feature is related to a source BMP_POIS, the system should populate target.BMPPOI.BMPPOI_ID with the source.SW_TRACKING.SW_TRACKING_NUM.  

During this process, the following translation has to be made:
Strip the "BMP" prefix
Apply the "POI" prefix

This will work because the number trigger Ehsan setup ensures unique 6-digit characters for both the BMP_POIS.BMP_POI_NUM and SW_TRACKING_NUM.  See #27

**Comment by leeensminger** [comment]
self assigning until BMPPOIs can get populated to the target table successfully via ETL

**Comment by gerrykelly** [comment]
@leeensminger 
This should be resolved with fixing #66

**Comment by leeensminger** [comment]
Resolved
