### ISSUE TITLE
Removed land_use subtype from BMPPOI Template FGDBs > needs update at county

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#57]
@leeensminger @JuanitaMiles @dhenry-KCI 
I removed the land_use subtype from BMPPOI in the tenplate GDBs below.  They should be replaced at the county (this was causing a minor issue in the ETL and I believe was unintentional by MDE)

C:\Projects\BaltCoNPDES\ETL\Templates\\**MDE_empty_withDomains.gdb**\\FeatureClasses\BMPPOI
C:\Projects\BaltCoNPDES\ETL\Templates\**\MDE_empty_withDomains_unaltered.gdb**\\FeatureClasses\BMPPOI

**Comment by leeensminger** [comment]
Yes this would be correct and a required change.  @BC89 please update at the county.
