### ISSUE TITLE
Updating BMPPOI causes ETL to fail

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#58]
the ETL attempts to update the following fields in BMPPOI  (where BMPPOI.IMP_ACRES = 0 after a prior update).  
'IMP_ACRES',	'RCN_PRE',	'RCN_POST',	'RCN_WOODS',	'PE_REQ',	'PE_ADR',	'Q_PRE',	'Q_POST',	'Q_WOODS' 
The source for the fields is BaltCo SW_TRACKING.  A few of the fields are required by MDE but not by the county.  So it worked with our test data, now fails with real data because of null values.  I am letting the MDE table permit nulls running on my VM to try to get the process to complete.  But it will fail in AGS and you'll need to come up with the resolution.  If it is not simply allowing nulls like I did, let me know if I need to revise logic or processing.

**Comment by leeensminger** [comment]
@gerrykelly What is the source for IMP_ACRES?

**Comment by leeensminger** [comment]
@gerrykelly no additional logic needed on your end for these selection sets.  It is up to the county to populate required fields.
