### ISSUE TITLE
Stormwater - Selection Set 1A - selection set is incorrect

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#59]
Using this selection on source.SW_TRACKING in SDE, I get 4058 results (be aware that one of these still has a dupe SW_TRACK_ID that is not included in the 4058):

1. Remove all SW_TRACKING records related to source.BMP_POIS
1a. Select from source.BMPS, where: BMP_POI_ID IS NULL
1b. From source.BMPS, find all related source.SW_TRACKING records.

2. Select from SW_TRACKING
2a. From results of 1b, _Select from current selection_, and apply this query:
IMPL_STATUS NOT IN ( 'Plan Revised', 'Duplicate Record', 'Unknown') AND REPORTING_YEAR <= '2017' AND TRACKING_STATUS <> 'Archived' AND CON_PURPOSE = 'New Development' 

Of these, I found all were migrated into the output (either BMP table, or the append_failure_bmp table) except 1133 records.  Those records are exported here: 
M:\2016\181603168.02\Reports\MDE_ETL\Testing\Stormwater\Outputs_forGerry\Issue_43.gdb\SelectionSet_1A_bmps_not_migrated_1133

At this time I am not sure why these were not included in the selection set.  The total intended selection set is here:
M:\2016\181603168.02\Reports\MDE_ETL\Testing\Stormwater\Outputs_forGerry\Issue_43.gdb\SelectionSet_intended_selection_set_all_4058

**Comment by leeensminger** [comment]
Previous work has been done on this issue in #43

**Comment by gerrykelly** [comment]
just as a record, this is the single query that produces the selection set of 4058 records described:
SELECT    b.objectid,   sw.IMPL_STATUS,      b.bmp_poi_id,     b.bmp_status,    b.reporting_year, 
sw.objectid,    sw.sw_track_id,    sw.parent_id,    sw.bmp_id,        sw.con_purpose,       sw.tracking_status,    sw.bmp_type,    sw.bmp_class,     sw.reporting_year
FROM   bmps_evw b inner join sw_tracking_evw sw on sw.BMP_ID = b.BMP_ID
where b.REPORTING_YEAR <= '2017' and b.BMP_POI_ID is null
and sw.IMPL_STATUS NOT IN ( 'Plan Revised', 'Duplicate Record', 'Unknown') 
  AND sw.TRACKING_STATUS <> 'Archived' AND sw.CON_PURPOSE = 'New Development'

**Comment by leeensminger** [comment]
For Reporting Year, I am incorrect - sorry.  It should be an "<=", not just "=".  I've updated the original comment.

**Comment by leeensminger** [comment]
Actually, I am incorrect... the query should get Reporting Year as "<=", not just an "=".  The results are the same for this current set of data, but wanted to clarify.  Sorry for any confusion.

**Comment by gerrykelly** [comment]
@leeensminger  Right and that is what I am doing in code.  My initial selection set actually matches yours, with the exception that I also require BMP_TYPE <> 'Unknown'
That extra clause gets me down to 3910 from your 4058.  So I still need to figure out what goes on after the initial selection, but should I remove that "BMP_TYPE <> 'Unknown'" clause, or should you add it to your logic? (I must have gotten that criteria from you somewhere along the way, but don't remember when)

**Comment by gerrykelly** [comment]
@leeensminger 
another logic difference on my side that does not change the numbers in the case of this data, so just as an FYI, is that rather than simply checking if BMPS.BMP_POI_ID IS NULL or not, I validate where the value is valid.  They all are in this case,

**Comment by leeensminger** [comment]
@gerrykelly Thanks for the reminder, you should keep BMP_TYPE <> Unknown.  I will add that to my logic.

**Comment by leeensminger** [comment]
@gerrykelly Of the 1133 records that were "missing" from the ETL migration output, this logic piece accounts for 148.  This yields a new total of 985 expected records that are missing from the output.

**Comment by gerrykelly** [comment]
@leeensminger 
Also, I thought in all cases we were excluding BMP_STATUS in ('Cancelled','Duplicate','Proposed')
That's a big deal and basically just about accounts for the discrepancy.  Let me know if the the additional clause " and not BMP_STATUS in ('Cancelled','Duplicate','Proposed')" is correct.
If it is, please give me a fresh start with you running your analysis with this clause and the "BMP_TYPE <> 'Unknown'" added.
I'm going to hold off on further work here until we get on the same page for this.

**Comment by leeensminger** [comment]
@gerrykelly You are correct, we should be excluding [BMP_STATUS in ('Cancelled','Duplicate','Proposed')] - sorry for the oversight on my part.  So it appears then that 10 remain.  After looking at these, they are all part of proposed conversions.  I'm looking into conversions now, but if these 10 are excluded from this selection set that appears correct.

Closing the issue.
