### ISSUE TITLE
D_SW_BMPType > dBMPType ... no matches for new domain codes

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#6]
We added 

Underground   Detention
Underground Extended Detention
Unknown

There are a number of dBMPType values not used by BalcCo, but none seem to match the new value, so I'll match them all to OTH for now

**Comment by leeensminger** [comment]
Match all of these to "OTH".

**Comment by gerrykelly** [comment]
I checked this.  It should already be good.  I'll just assign it back to you to close if agreed.  
![image](https://user-images.githubusercontent.com/8259136/32291615-f924cba0-bf13-11e7-9cb0-0130c85a1e45.png)

**Comment by leeensminger** [comment]
Good to go, I should've closed it in the first place, sorry
