### ISSUE TITLE
Selection set 1D - POIS - target.BMPPOI.IMP_ACRES is not populating correctly

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#63]
Based upon the documentation, I expect to see target.BMPPOI.IMP_ACRES sourced from SW_TRACKING.IMP_ACRES.  Currently, all outputted BMPPOI.IMP_ACRES are null, and thus causing a failure.

This may be related to the fact that for this selection set, 1 BMPPOI may have many BMPS, and therefore many SW_TRACKING records.  So I'm not sure how we can pull many values into 1 BMPPOI record.

What is the current source of target.BMPPOI.IMP_ACRES?

**Comment by gerrykelly** [comment]
@leeensminger 
This (and other fields) should now be populating for all BMPPOI records (but maybe worth spot-checking a value or two for records coming from each of the selection sets)

**Comment by leeensminger** [comment]
Resolved
