### ISSUE TITLE
Selection Set 1A - target BMP.BMPPOI_ID does not include county code + yr

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#65]
In the BMP.BMPPOI_ID output for this selection set, the values are outputted as "POI12345", instead of the BA+yy(year) +POI123456.

![image](https://user-images.githubusercontent.com/4103847/36574793-56d0ed38-1815-11e8-9cec-565b728409dd.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Should be OK now

**Comment by leeensminger** [comment]
Resolved
