### ISSUE TITLE
Selection Set C - Parts 1 and 2 - BMPPOI.BMPPOI_ID values are not replaced with "POI"

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#66]
in the BMP.BMPPOI_ID field, values are brought in with their associated BMP ID, like "BA99BMP123456".  The "BMP" component of this is then stripped and replaced with "POI".  For selection set C, this strip/replace does not occur, and values remain populated with the "BMP".

![image](https://user-images.githubusercontent.com/4103847/36575057-b98b9a4e-1816-11e8-8400-58dd6b947537.png)

**Comment by leeensminger** [comment]
Related to #52

**Comment by gerrykelly** [comment]
@leeensminger 
I think this is now working in the GP service, but what's odd is this same code will not work in it my development version.  (It should ... ESRI bug).  I'm going to write it a different way and see if I can get it to work in both environments.

**Comment by leeensminger** [comment]
Looks OK

**Comment by leeensminger** [comment]
Looks like its working OK
