### ISSUE TITLE
Selection Set 1A - TRACKING_STATUS filter is not correct

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#67]
Selection Set 1A dictates that SW_TRACKING.TRACKING_STATUS should <> Archived.  Currently, features with SW_TRACKING.TRACKING_STATUS = Archived are being migrated to the target BMPPOI feature class.  These Archived records are currently NOT being migrated to BMP (so target BMP table part is correct).  

They are being migrated because they have a 1999 reporting year, because they are part of the Selection Set 1C Part 2.   However, using Reporting Year, I did not run the report for 1C.

The Selection Set 1A needs to only include where SW_TRACKING.TRACKING_STATUS <> Archived.

**Comment by leeensminger** [comment]
Also - target BMPInspections are related to BMPs.  And the BMPInspections table includes inspections for these Archived records - they have an BMP_ID, and interestingly, because the BMP table records are not present, these inspections are orphaned.  The inspections should not be loaded to target either.

**Comment by leeensminger** [comment]
Also, in the same way that the inspections are being loaded, so are drainage areas.

**Comment by gerrykelly** [comment]
@leeensminger 
I don't think this would have come up without the issue of different reporting years for related elements, but it's good to fix it properly, hopefully I have (I tested running the GP for RY 2010 and 2023)

**Comment by leeensminger** [comment]
Appears resolved
