### ISSUE TITLE
Stormwater - BMP DA - Selection Set 1C ghosted BMP DAs are being migrated

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#69]
This is discussed in the second comment of #67 :
_Also, in the same way that the inspections are being loaded, so are drainage areas._

Archived records are being inadvertently migrated to BMPPOI, but shouldn't be, based on SW_TRACKING.TRACKING_STATUS. The DAs related to these facilities are also being loaded to BMPDrainageAreas, and shouldn't be.

**Comment by gerrykelly** [comment]
@leeensminger 
Getting the DAs uses far and away the biggest most complex query in the ETL.  I finally just edited so if records in any way trace back to TRACKING_STATUS = 'Archived' they are excluded.  Hopefully that worked.

**Comment by leeensminger** [comment]
Looks good for set 1A.  I'll test for 1C, because I'm not sure that's the best approach for those.

**Comment by leeensminger** [comment]
Yes I think that works.
