### ISSUE TITLE
INSP_SW.INSP_SW_NUM null (trigger not working as expected?)

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#7]
This trigger only populates INSP_SW_NUM when it finds the SW_TRACK_ID of the inserted-row in  SW_TRACKING.  So if the related GUIDs are good it should work if the data-load sequence has SW_TRACKING load first (and presumably the UI handles this correctly, but defintely a case where we should enforce the FK constraint or give the trigger a fallback.

(I just calced dummy values for now)

Are there other conditional trigger that could have the same problem?

TRIGGER "BEFORE_ADD_INSP_SW"
  BEFORE INSERT ON "INSP_SW"FOR EACH ROW
  DECLARE
  l_purpose VARCHAR(30);
BEGIN
  BEGIN
    SELECT CON_PURPOSE INTO l_purpose FROM SW_TRACKING WHERE SW_TRACK_ID = :new.SW_TRACK_ID;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    l_purpose := NULL;
  END;  
  IF l_purpose IS NOT NULL THEN
    IF l_purpose = SHARED.conversionConPurpose OR
       l_purpose = SHARED.restorationConPurpose  THEN
      :new.INSP_SW_NUM := 'RIN' || SHARED.GENERATEMDENUM('RIN');
    ELSE 
      :new.INSP_SW_NUM := 'BIN' || SHARED.GENERATEMDENUM('BIN');  
    END IF;
  END IF;  
END;

**Comment by leeensminger** [comment]
I'm calling this a data management issue, and if end users use the tool as it is designed, this should not be a problem.  If they manipulate data using ArcGIS, they open the door for this issue.  

Closing this, but if I'm not correct @BC89 @gerrykelly reopen and advise.
