### ISSUE TITLE
Selection Set 1C - target BMP.BMPPOI values do not include "POI" value

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#70]
Likely related to #52 .  The BMPPOI field in outputted BMP table also need to have "BMP" stripped and replaced with "POI".  This field is the PK and FK in each of these BMP and BMPOI tables.
![image](https://user-images.githubusercontent.com/4103847/36637214-2005e1c8-19a5-11e8-8291-dac941f5c61d.png)

**Comment by gerrykelly** [comment]
@leeensminger 
should be fixed for good this time

**Comment by leeensminger** [comment]
Appears ok
