### ISSUE TITLE
AltBMPPoly - Annual Practice Areas - no output to target?

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#72]
I have Annual Practice Areas records that I'd expect to see in the output.  When I look at the output, I see _TREE_INFO to AltBMPPoly_ and _IMPERVIOUS_REM to AltBMPPoly_, but not annual practice areas (inlet cleaning and street sweeping).  Please confirm the ETL still provides for this.

![image](https://user-images.githubusercontent.com/4103847/36642547-bfed7426-1a0e-11e8-946d-e9207ef2e18b.png)

**Comment by gerrykelly** [comment]
@leeensminger 
This should be restored now (another issue with how featureclasses in a featuredataset are handled)

**Comment by leeensminger** [comment]
Appears resolved
