### ISSUE TITLE
AltBMPPoly - Reforestation - Update selection set for Implementation Status

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#73]
The selection set for Reforestation also needs to be updated for the new domain values in D_Impl_Status. Values Duplicate Record, Plan Revised, and Unknown need to be excluded from the selection set, so they don't go to MDE.

Same as #4

**Comment by gerrykelly** [comment]
@leeensminger done

**Comment by leeensminger** [comment]
Appears resolved
