### ISSUE TITLE
Inspections for RestBMPs are not outputted to target gdb

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#77]
Output table RestBMPInspections is consistently empty.  Records are expected in this table for selection set 1B, and 1C ("new" BMPs... with sw_tracking_status = Current), and for both selection sets, the target table RestBMPInspections is empty.

For selection set 1B, I would expect three records in the output RestBMPInspections table - those three records are highlighted in the middle table below:
![image](https://user-images.githubusercontent.com/4103847/36947048-c053f81e-1f94-11e8-969b-864fa286a56a.png)

**Comment by gerrykelly** [comment]
@leeensminger 
I see what you mean if I am to use records from SW_INSP_REPORT to populate RestBMPInspections .  Although the ETL documentation workbook shows this on the selection set sheet, on the main ETL sheet I only ever saw the source for RestBMPInspections as only INSP_SW (which is empty).  I'll work on new code and revision that will get the related SW_INSP_REPORT into RestBMPInspections

**Comment by gerrykelly** [comment]
@leeensminger 
I've made the update and I get 3 (but only 3) RestBMPInspections  using RY 2012.  There is no MDE relationship class for RestBMPs > RestBMPInspections  (correct? seems like there sure should be), but the join in ArcMap verifies that I'm getting something right.

**Comment by leeensminger** [comment]
@gerrykelly 3 records for 1B is correct.  There is no MDE relationship clas for RestBMPs > restBMPInspections.... there should be, but that is a mistake in their database.  At this time, for this initial deploy, we're not on the hook to provide it, since it wasn't in the template gdb.

**Comment by leeensminger** [comment]
Appears resolved
