### ISSUE TITLE
Gaps between polygons in base layers mean NPDES feature missing from spatial views

### ISSUE THREAD

**Issue by gerrykelly** [kcigeospatial/balt_co_ETL#9]
This will cause an ETL failure.  I know it happens for land-use at least.

**Comment by leeensminger** [comment]
I have some thoughts, let's discuss as a team on Monday.  Need to finalize this.

**Comment by leeensminger** [comment]
Dev team decided to let these come through as errors

**Comment by leeensminger** [comment]
Confirmed with Rob H. that this is the best way forward.
