### ISSUE TITLE
Update translation for 8 digit watershed values

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#92]
Values in NCT D_Watershed8dgt are not mapping properly to MDE's 8 digit watershed values.  Specifically:
NCT domain value:
Code: 02130807-Middle River
Desc: 02130807-Middle River

Needs to map to the following MDE domain (but currently is showing an error, and is showing a _Failed to replace_ error in the output logs.

MDE domain dMD8digit:
Code: 02130807
Desc: Middle River - Browns

@gerrykelly Please ensure these domains are **_all_** being mapped correctly.  The translation should be straightforward but I can provide a mapping if needed.

**Comment by dhenry-KCI** [comment]
I thought I saw he closed this one. Is that not the case?

Sent from my iPhone

On Apr 19, 2018, at 7:11 PM, Lee Ensminger <notifications@github.com<mailto:notifications@github.com>> wrote:


Values in NCT D_Watershed8dgt are not mapping properly to MDE's 8 digit watershed values. Specifically:
NCT domain value:
Code: 02130807-Middle River
Desc: 02130807-Middle River

Needs to map to the following MDE domain (but currently is showing an error, and is showing a Failed to replace error in the output logs.

MDE domain dMD8digit:
Code: 02130807
Desc: Middle River - Browns

@gerrykelly<https://github.com/gerrykelly> Please ensure these domains are all being mapped correctly. The translation should be straightforward but I can provide a mapping if needed.

-
